Feature: Union schema compatibility
fivetran/dbt_tiktok_ads_source pull request #12
Opened 2023-09-01 22:45 UTC by fivetran-catfritz

Issue: 

Confirm the following files were correctly updated automatically:
- [ ] CHANGELOG
- [ ] README
- [ ] stg_facebook_ads.yml, src_facebook_ads.yml, facebook_ads.yml (depending if source or transform)
- [ ] docs.md
- [ ] joins
- [ ] window functions (partition by)
- [ ] 'source_relation' column added in staging and transform models
- [ ] tests

Manual updates:
- [ ] Add `source_relation` to downstream models if necessary
- [ ] Finish any incomplete/incorrect joins/partitions
- [ ] Update tests to include `source_relation` in unique-combination-of-cols if necessary
    - May need to remove some uniqueness tests in favor of the combo test

Validation:
- [ ] `dbt run` locally passes
- [ ] `dbt test` locally passes

2023-09-06 21:50 UTC, fivetran-catfritz commented
Note--we need to decide if we update identifiers for 
1.`...adreport...` tables (vs ad_report with the underscore)
2. double underscore identifiers 

or update fivetran_utils.union_data to handle divergent naming.

It technically passes buildkite, but reviewing the logs, it can't find a lot of the seed tables because of the identifier issues, which would mean problems for others using identifiers.

2023-09-26 15:28 UTC, fivetran-joemarkiewicz requested changes
This looks great, I noticed that in the integration tests however the ad group seed is not being found. Do you know why that may be? It compiles fine when running with production data. Can we resolve this so the integration tests use all the seed files. Once that is resolved this will be good to go!

2023-09-26 15:28 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to update before merge

2023-09-29 21:44 UTC, fivetran-catfritz commented
Updated identifier discrepancies. All tables found in latest integration tests!

2023-10-03 14:35 UTC, fivetran-joemarkiewicz approved these changes
Thanks for making the update! I have just one more small request to update the CHANGELOG and README. Once those are applied this will be good to merge and release once all the others are approved.

2023-10-03 14:35 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Unioning capability! This adds the ability to union source data from multiple tiktok_ads connectors. Refer to the [README](https://github.com/fivetran/dbt_tiktok_ads_source/blob/main/README.md) for
Actually, can we remove the README "hide" sections in these updates. This way we are able to link directly to the section in the README where the users needs to understand how to configure the union feature.

Otherwise, I worry this cool feature is hidden from people actually using it.

2023-10-09 16:22 UTC, fivetran-catfritz commented on CHANGELOG.md
> +- Unioning capability! This adds the ability to union source data from multiple tiktok_ads connectors. Refer to the [README](https://github.com/fivetran/dbt_tiktok_ads_source/blob/main/README.md) for
Updated.

2023-10-12 02:16 UTC, fivetran-catfritz commented
Merging for release on 12-Oct-2023.

2023-10-12 02:16 UTC, merged